dir = File.dirname(__FILE__)
require "#{dir}/predicates/base"
require "#{dir}/predicates/predicate"
require "#{dir}/predicates/binary_predicate"
require "#{dir}/predicates/equal_to"
require "#{dir}/predicates/not_equal_to"
require "#{dir}/predicates/greater_than"
require "#{dir}/predicates/less_than"
require "#{dir}/predicates/greater_than_or_equal_to"
require "#{dir}/predicates/less_than_or_equal_to"
require "#{dir}/predicates/composite_predicate"
require "#{dir}/predicates/and"
require "#{dir}/predicates/or"