dir = File.dirname(__FILE__)
require "#{dir}/relations/relation"
require "#{dir}/relations/composite_relation"
require "#{dir}/relations/set"
require "#{dir}/relations/singleton_relation"
require "#{dir}/relations/selection"
require "#{dir}/relations/inner_join"
require "#{dir}/relations/set_projection"
require "#{dir}/relations/attributes_projection"
require "#{dir}/relations/ordering"
require "#{dir}/relations/tuple_relation_methods"
require "#{dir}/relations/belongs_to"
require "#{dir}/relations/has_one"
require "#{dir}/relations/has_many"
require "#{dir}/relations/has_many_through"
